name: Build and Push Docker Image

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout Code
      uses: actions/checkout@v3

    - name: Dockerhub-login
      uses: docker/login-action@v3
      with:
          username: ${{ vars.USERNAME }}
          password: ${{ vars.PASSWORD }}


    - name: Build the docker image
      run: |
          docker build -t dictonaryapp .
          docker tag dictonaryapp tapashdeb/dictonaryapp:latest

    - name: Push Image to docker hub
      run: |
          docker push tapashdeb/dictonaryapp:latest

